name: Build LVGL-MicroPython bin

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: ESP32_GENERIC_S3
            variant: SPIRAM_OCT
            display: st7796
            indev: ft6x36
            flash-size: 16MB
            extra: octal-flash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install host deps
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Install ESP-IDF & toolchains
      run: |
        git clone -b v5.3 --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
        ~/esp-idf/install.sh esp32s3
        echo "IDF_PATH=~/esp-idf" >> $GITHUB_ENV

    - name: Build
      run: |
        . ~/esp-idf/export.sh
        python -m pip install -r requirements.txt
        python make.py esp32 \
          BOARD=${{ matrix.board }} \
          BOARD_VARIANT=${{ matrix.variant }} \
          DISPLAY=${{ matrix.display }} \
          INDEV=${{ matrix.indev }} \
          flash-size=${{ matrix.flash-size }} \
          ${{ matrix.extra }}

    - name: Upload bin artifact
      uses: actions/upload-artifact@v4
      with:
        name: lvgl_micropy_${{ matrix.board }}-${{ matrix.flash-size }}.bin
        path: build/lvgl_micropy*.bin
